import Head from "next/head";
import React from "react";
import Aside from "./Aside";
import Footer from "./Footer";
import Header from "./Header";

function Layout({ children }) {
  return (
    <>
      {/* <Head>
        <title>layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
      </Head> */}

      {/* <Footer /> */}

      <>
        <body className="flex bg-gray-100 min-h-screen">
          {/* aside */}
          <Aside />
          <div className="flex-grow text-gray-800">
            {/* header */}
            <Header />
            {children}
          </div>
        </body>
      </>
    </>
  );
}

export default Layout;
